name: Update data.json Automatically

on:
  push:
    paths:
      - '**/*'  # Trigger on any change in the repo

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Run the generate_data_json.py script
      - name: Generate data.json
        run: python generate_data_json.py

      # Step 4: Commit and push updated data.json
      - name: Commit and push data.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git diff-index --quiet HEAD || git commit -m "Auto-update data.json"
          git push
